version: '3.8'

services:
  cpp-dev:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/PersonalProjects/MushroomKV/build/server:/app/server
    working_dir: /app
    stdin_open: true
    tty: true

